### PR TITLE
fix: preserve attributes when expiring cookies

### LINKED ISSUE #7352: `oauth_state` cookie is not removed after consumption
### Is this suited for github?

- [x] Yes, this is suited for github

### To Reproduce

With `account.storeStateStrategy: "cookie"` and an OAuth provider, go through a successful login flow and observe the `Set-Cookie:` headers along the way.

### Current vs. Expected behavior

Current behavior: the `__Secure-better-auth.oauth_state` cookie is still there

Expected behavior: the `__Secure-better-auth.oauth_state` cookie is deleted/cleared after login completes and the cookie is consumed.

Observations:

Upon the POST to `/api/auth/sign-in/social`, this cookie is set:

```
__Secure-better-auth.oauth_state=...redacted...; Max-Age=600000; Path=/; HttpOnly; Secure; SameSite=Lax
```

Upon the GET to `/api/auth/callback/providername`, this cookie is set:

```
__Secure-better-auth.oauth_state=; Max-Age=0; Secure
```

However the browser would not respect this deletion of the cookie as the `Path` does not match. The `Path` should also be set when clearing the cookie in order to successfully clear it. This is done in the codebase on some code paths, but not for this `oauth_state` cookie.

### What version of Better Auth are you using?

1.4.10

### System info

```bash
{
  "system": {
    "platform": "linux",
    "arch": "arm64",
    "version": "#51-Ubuntu SMP PREEMPT_DYNAMIC Sat Nov  9 18:03:35 UTC 2024",
    "release": "6.8.0-50-generic",
    "cpuCount": 3,
    "cpuModel": "unknown",
    "totalMemory": "9.69 GB",
    "freeMemory": "5.64 GB"
  },
  "node": {
    "version": "v24.10.0",
    "env": "development"
  },
  "packageManager": {
    "name": "npm",
    "version": "11.6.1"
  },
  "frameworks": [
    {
      "name": "express",
      "version": "^5.2.1"
    },
    {
      "name": "astro",
      "version": "^5.16.6"
    }
  ],
  "databases": null,
  "betterAuth": {
    "version": "^1.4.10",
    "config": {
      "baseURL": "http://localhost:4321",
      "secret": "[REDACTED]",
      "session": {
        "cookieCache": {
          "enabled": true,
          "maxAge": 172800,
          "strategy": "jwe",
          "refreshCache": true
        }
      },
      "account": {
        "storeStateStrategy": "cookie",
        "storeAccountCookie": true
      },
      "plugins": [
        {
          "name": "custom-social-providers",
          "config": {
            "id": "custom-social-providers"
          }
        },
        {
          "name": "oauth-proxy",
          "config": {
            "id": "oauth-proxy",
            "options": {},
            "endpoints": {},
            "hooks": {
              "before": [
                {},
                {},
                {}
              ],
              "after": [
                {},
                {},
                {}
              ]
            }
          }
        }
      ]
    }
  }
}
```

### Which area(s) are affected? (Select all that apply)

Backend

### Auth config (if applicable)

```typescript

```

### Additional context

I was using a Microsoft Entra ID social provider but I don't think it affects this, the key thing is that it is in the stateless mode config without database.

### PR DESCRIPTION
**Pull request by bytaesu**
> [!NOTE]
> Reference:
> If the cookie store contains a cookie with the same `name`, `domain`, and `path` as the newly created cookie ...
> https://datatracker.ietf.org/doc/html/rfc6265#section-5.3 

This PR centralizes cookie expiration logic and includes attributes in the expiration process.

- Closes #7352

---
## Summary by cubic
Fixes cookie expiration by preserving original attributes (path, domain, secure, httpOnly) so deletions work reliably across all flows. Centralizes the logic with expireCookie and adds tests; closes #7352.

- **Bug Fixes**
  - Expire cookies with maxAge: 0 while keeping existing attributes.
  - Correctly delete state/admin/OIDC/multi-session/two-factor cookies with custom paths.
  - Add regression tests for expireCookie and OAuth state cookie attributes.

- **Refactors**
  - Introduce expireCookie(ctx, cookie) and replace manual deletions (session, account, oauth_state, etc.).
  - Standardize cookie config to BetterAuthCookie { name, attributes } and migrate all cookie.options usages to cookie.attributes.

<sup>Written for commit 41f4dabcec985dcef6460e6ce6f68e24651c737c. Summary will update on new commits.</sup>

### CODE REVIEW

**Comment by bytaesu** [comment]
@claude,

Review if this PR goal is correct and whether refactoring to the centralized logic breaks any functionality.

File: packages/better-auth/src/cookies/index.ts [hunk 1]
```diff
@@ -293,25 +294,30 @@ export async function setSessionCookie(
...
+ */
+export function expireCookie(
 	ctx: GenericEndpointContext,
-	skipDontRememberMe?: boolean | undefined,
+	cookie: BetterAuthCookie,
 ) {
-	ctx.setCookie(ctx.context.authCookies.sessionToken.name, "", {
-		...ctx.context.authCookies.sessionToken.options,
+	const cookieOptions =
+		"options" in cookie ? cookie.options : cookie.attributes;
```
[the remark this answers is not in the document]
Comment (bytaesu) [reply packages/better-auth/src/cookies/index.ts]: Changing the return type of createAuthCookie() could be a breaking change.. will adjust at an appropriate time later.

File: packages/core/src/types/cookie.ts [hunk 2]
```diff
@@ -1,5 +1,10 @@
 import type { CookieOptions } from "better-call";
 
+// TODO: keep only one of options or attributes
+export type BetterAuthCookie =
+	| { name: string; options: CookieOptions }
+	| { name: string; attributes: CookieOptions };
```
[the remark this answers is not in the document]
Comment (bytaesu) [reply packages/core/src/types/cookie.ts]: Changing the return type of createAuthCookie() could be a breaking change.. will adjust at an appropriate time later.

File: packages/core/src/types/cookie.ts [hunk 3]
```diff
@@ -1,5 +1,10 @@
 import type { CookieOptions } from "better-call";
 
+// TODO: keep only one of options or attributes
```
Comment (himself65) [inline packages/core/src/types/cookie.ts]: Can we remove this TODO? What does this mean?

Comment (bytaesu) [reply packages/core/src/types/cookie.ts]: - `ctx.context.createAuthCookie()`: { name: string, attributes: CookieOptions }
- `ctx.context.authCookies.XXXXXX`: { name: string, options: CookieOptions }

Basically the same type, but the shape is different. I think we need to standardize it, but changing it now could be breaking change i guess..🤔 @himself65

Comment (bytaesu) [reply packages/core/src/types/cookie.ts]: Should I remove the comment or keep it?

**Comment by himself65** [comment]
Have a discussion with Bereket, and we use `attributes.`

**Comment by himself65** [comment]
@claude, can you rename related code to use `attributes` instead of `options` to avoid the breaking change?

**Review by himself65 — APPROVED** [review]

**Comment by himself65** [comment]
@claude Please fix typecheck error

```shell
Error: packages/better-auth/src/plugins/last-login-method/index.ts(156,50): error TS2339: Property 'options' does not exist on type 'BetterAuthCookie'.
Error: packages/better-auth/src/plugins/mcp/index.ts(210,8): error TS2353: Object literal may only specify known properties, and 'options' does not exist in type 'BetterAuthCookie'.
Error: packages/better-auth/src/plugins/oidc-provider/index.ts(406,8): error TS2353: Object literal may only specify known properties, and 'options' does not exist in type 'BetterAuthCookie'.
Error: packages/better-auth/src/plugins/oidc-provider/index.ts(586,7): error TS2353: Object literal may only specify known properties, and 'options' does not exist in type 'BetterAuthCookie'.
 ELIFECYCLE  Command failed with exit code 2.
```
