### PR TITLE
fix(rate-limiter): handle missing IP address in rate limit function

### LINKED ISSUE #1958: nullish value on ratelimit key filed
### Is this suited for github?

- [x] Yes, this is suited for github

### To Reproduce

Just configure a rate limit on a route (or all routes) and use database as your storage.

### Current vs. Expected behavior

-

### What version of Better Auth are you using?

1.2.4

### Provide environment information

```bash
- OS [Windows 11]
- Browser: [Chrome]
- API Client: [Better Auth's Scala]
```

### Which area(s) are affected? (Select all that apply)

Package

### Auth config (if applicable)

```typescript
import { betterAuth } from "better-auth";
import { Pool } from "pg";
import { openAPI, phoneNumber } from "better-auth/plugins";

export const auth = betterAuth({
  emailAndPassword: {
    enabled: true,
  },
  rateLimit: {
    storage: "database",
    window: parseInt(Bun.env.RATE_LIMIT_TIME_WINDOW ?? "60"),
    max: parseInt(Bun.env.MAX_TRIES ?? "1"),
    enabled: true,
  },
 database: new Pool({
    connectionString: Bun.env.POSTGRES_STRING,
  }),
plugins: [
    openAPI(),
    phoneNumber({
      sendOTP({ phoneNumber, code }, request) {
        console.log(`Sending code: ${code} to phone number: ${phoneNumber}`);
      },

      signUpOnVerification: {
        getTempEmail: (phoneNumber) => {
          return `${phoneNumber}@example.com`;
        },
        //optionally, you can also pass `getTempName` function to generate a temporary name for the user
        getTempName: (phoneNumber) => {
          return phoneNumber; //by default, it will use the phone number as the name
        },
      },
    }),
  ]
)}
```

### Additional context

Hi, I hope you're having some fun time (like us using better-auth)!
I wanted to mention that there's some nullish value on ratelimit key field when the storage is set to database (haven't tested the custom-storage).

here's the photo:

Image

### PR DESCRIPTION
**Pull request by Bekacru**
closes #1958

### CODE REVIEW

File: packages/better-auth/src/api/rate-limiter/index.ts [hunk 1]
```diff
@@ -119,7 +119,11 @@ export async function onRequestRateLimit(req: Request, ctx: AuthContext) {
 	);
 	let window = ctx.rateLimit.window;
 	let max = ctx.rateLimit.max;
-	const key = getIp(req, ctx.options) + path;
+	const ip = getIp(req, ctx.options);
+	if (!ip) {
+		return;
```
Comment (drakmail) [inline packages/better-auth/src/api/rate-limiter/index.ts:124]: shouldn’t this completely skip rate limits checks if an ip can’t be determined?
