### PR TITLE
fix: resolve dynamic baseURL for direct `auth.api` calls

### LINKED ISSUE #9105: signInMagicLink throw Invalid URL when using baseURL: { .... }
### Is this suited for github?

- [x] Yes, this is suited for github

### Reproduction

1. Configure betterAuth with: 

```
import { betterAuth } from "better-auth"

const LOCAL_DEV_ORIGINS = [
  'localhost:3000',
  'localhost:3010',
]

export const auth = betterAuth({
  baseURL: {
    allowedHosts: [...LOCAL_DEV_ORIGINS],
    protocol: process.env.NODE_ENV === 'development' ? 'http' : 'https',
  },
});
```

2. use magic link:
```
    await auth.api.signInMagicLink({
      body: { email, callbackURL: '/' },
      headers: request.headers,
    })
```

### Current vs. Expected behavior

signInMagicLink should not throw

### What version of Better Auth are you using?

1.6.0

### System info

```bash
{
  "system": {
    "platform": "win32",
    "arch": "x64",
    "version": "Windows 11 Pro",
    "release": "10.0.26200",
    "cpuCount": 16,
    "cpuModel": "AMD Ryzen 7 9800X3D 8-Core Processor           ",
    "totalMemory": "31.06 GB",
    "freeMemory": "13.24 GB"
  },
  "node": {
    "version": "v24.6.0",
    "env": "development"
  },
  "packageManager": {
    "name": "npm",
    "version": "11.5.1"
  },
  "frameworks": [
    {
      "name": "react",
      "version": "^19.2.5"
    }
  ],
  "databases": [
    {
      "name": "pg",
      "version": "^8.20.0"
    },
    {
      "name": "drizzle",
      "version": "^0.45.2"
    }
  ],
  "betterAuth": {
    "version": "^1.6.2",
    "config": {
      "baseURL": {
        "allowedHosts": [
          "localhost:3000",
          "localhost:3010",
          "127.0.0.1:3000",
          "*.railway.app"
        ],
        "protocol": "https"
      },
      "advanced": {
        "cookiePrefix": "gcf-paie",
        "crossSubDomainCookies": {
          "enabled": true
        }
      },
      "account": {
        "accountLinking": {
          "allowDifferentEmails": true,
          "trustedProviders": [
            "scheduler"
          ]
        }
      },
      "user": {
        "additionalFields": {
          "matricule": {
            "type": "string",
            "required": false,
            "nullable": true,
            "input": false,
            "returned": true
          },
          "approvedAt": {
            "type": "date",
            "required": false,
            "nullable": true,
            "input": false,
            "returned": true
          }
        }
      },
      "telemetry": {
        "enabled": true,
        "debug": false
      },
      "logger": {
        "disabled": false,
        "disableColors": false,
        "level": "debug"
      },
      "plugins": [
        {
          "name": "magic-link",
          "config": {
            "id": "magic-link",
            "version": "1.6.0",
            "endpoints": {},
            "rateLimit": [
              {
                "window": 60,
                "max": 5
              }
            ],
            "options": {}
          }
        },
        {
          "name": "admin",
          "config": {
            "id": "admin",
            "version": "1.6.0",
            "hooks": {
              "after": [
                {}
              ]
            },
            "endpoints": {},
            "$ERROR_CODES": {
              "FAILED_TO_CREATE_USER": {
                "code": "FAILED_TO_CREATE_USER",
                "message": "Failed to create user"
              },
              "USER_ALREADY_EXISTS": {
                "code": "USER_ALREADY_EXISTS",
                "message": "User already exists."
              },
              "USER_ALREADY_EXISTS_USE_ANOTHER_EMAIL": {
                "code": "USER_ALREADY_EXISTS_USE_ANOTHER_EMAIL",
                "message": "User already exists. Use another email."
              },
              "YOU_CANNOT_BAN_YOURSELF": {
                "code": "YOU_CANNOT_BAN_YOURSELF",
                "message": "You cannot ban yourself"
              },
              "YOU_ARE_NOT_ALLOWED_TO_CHANGE_USERS_ROLE": {
                "code": "YOU_ARE_NOT_ALLOWED_TO_CHANGE_USERS_ROLE",
                "message": "You are not allowed to change users role"
              },
              "YOU_ARE_NOT_ALLOWED_TO_CREATE_USERS": {
                "code": "YOU_ARE_NOT_ALLOWED_TO_CREATE_USERS",
                "message": "You are not allowed to create users"
              },
              "YOU_ARE_NOT_ALLOWED_TO_LIST_USERS": {
                "code": "YOU_ARE_NOT_ALLOWED_TO_LIST_USERS",
                "message": "You are not allowed to list users"
              },
              "YOU_ARE_NOT_ALLOWED_TO_LIST_USERS_SESSIONS": {
                "code": "YOU_ARE_NOT_ALLOWED_TO_LIST_USERS_SESSIONS",
                "message": "You are not allowed to list users sessions"
              },
              "YOU_ARE_NOT_ALLOWED_TO_BAN_USERS": {
                "code": "YOU_ARE_NOT_ALLOWED_TO_BAN_USERS",
                "message": "You are not allowed to ban users"
              },
              "YOU_ARE_NOT_ALLOWED_TO_IMPERSONATE_USERS": {
                "code": "YOU_ARE_NOT_ALLOWED_TO_IMPERSONATE_USERS",
                "message": "You are not allowed to impersonate users"
              },
              "YOU_ARE_NOT_ALLOWED_TO_REVOKE_USERS_SESSIONS": {
                "code": "YOU_ARE_NOT_ALLOWED_TO_REVOKE_USERS_SESSIONS",
                "message": "You are not allowed to revoke users sessions"
              },
              "YOU_ARE_NOT_ALLOWED_TO_DELETE_USERS": {
                "code": "YOU_ARE_NOT_ALLOWED_TO_DELETE_USERS",
                "message": "You are not allowed to delete users"
              },
              "YOU_ARE_NOT_ALLOWED_TO_SET_USERS_PASSWORD": {
                "code": "YOU_ARE_NOT_ALLOWED_TO_SET_USERS_PASSWORD",
                "message": "You are not allowed to set users password"
              },
              "BANNED_USER": {
                "code": "BANNED_USER",
                "message": "You have been banned from this application"
              },
              "YOU_ARE_NOT_ALLOWED_TO_GET_USER": {
                "code": "YOU_ARE_NOT_ALLOWED_TO_GET_USER",
                "message": "You are not allowed to get user"
              },
              "NO_DATA_TO_UPDATE": {
                "code": "NO_DATA_TO_UPDATE",
                "message": "No data to update"
              },
              "YOU_ARE_NOT_ALLOWED_TO_UPDATE_USERS": {
                "code": "YOU_ARE_NOT_ALLOWED_TO_UPDATE_USERS",
                "message": "You are not allowed to update users"
              },
              "YOU_CANNOT_REMOVE_YOURSELF": {
                "code": "YOU_CANNOT_REMOVE_YOURSELF",
                "message": "You cannot remove yourself"
              },
              "YOU_ARE_NOT_ALLOWED_TO_SET_NON_EXISTENT_VALUE": {
                "code": "YOU_ARE_NOT_ALLOWED_TO_SET_NON_EXISTENT_VALUE",
                "message": "You are not allowed to set a non-existent role value"
              },
              "YOU_CANNOT_IMPERSONATE_ADMINS": {
                "code": "YOU_CANNOT_IMPERSONATE_ADMINS",
                "message": "You cannot impersonate admins"
              },
              "INVALID_ROLE_TYPE": {
                "code": "INVALID_ROLE_TYPE",
                "message": "Invalid role type"
              }
            },
            "schema": {
              "user": {
                "fields": {
                  "role": {
                    "type": "string",
                    "required": false,
                    "input": false
                  },
                  "banned": {
                    "type": "boolean",
                    "defaultValue": false,
                    "required": false,
                    "input": false
                  },
                  "banReason": {
                    "type": "string",
                    "required": false,
                    "input": false
                  },
                  "banExpires": {
                    "type": "date",
                    "required": false,
                    "input": false
                  }
                }
              },
              "session": {
                "fields": {
                  "impersonatedBy": {
                    "type": "string",
                    "required": false
                  }
                }
              }
            },
            "options": {
              "ac": {
                "statements": {
                  "user": [
                    "create",
                    "list",
                    "set-role",
                    "ban",
                    "impersonate",
                    "impersonate-admins",
                    "delete",
                    "set-password",
                    "get",
                    "update"
                  ],
                  "session": [
                    "list",
                    "revoke",
                    "delete"
                  ],
                  "project": [
                    "read",
                    "manage"
                  ],
                  "validation": [
                    "review",
                    "finalize",
                    "report"
                  ],
                  "app": [
                    "admin-access",
                    "bypass-approval"
                  ],
                  "role": [
                    "manage-sensitive"
                  ]
                }
              },
              "roles": {
                "user": {
                  "statements": {
                    "project": [
                      "read"
                    ]
                  }
                },
                "supervisor": {
                  "statements": {
                    "project": [
                      "read",
                      "manage"
                    ],
                    "validation": [
                      "review",
                      "report"
                    ]
                  }
                },
                "admin": {
                  "statements": {
                    "user": [
                      "create",
                      "list",
                      "set-role",
                      "ban",
                      "impersonate",
                      "delete",
                      "set-password",
                      "get",
                      "update"
                    ],
                    "session": [
                      "list",
                      "revoke",
                      "delete"
                    ],
                    "project": [
                      "read",
                      "manage"
                    ],
                    "validation": [
                      "review",
                      "finalize",
                      "report"
                    ],
                    "app": [
                      "admin-access",
                      "bypass-approval"
                    ]
                  }
                },
                "superadmin": {
                  "statements": {
                    "user": [
                      "create",
                      "list",
                      "set-role",
                      "ban",
                      "impersonate",
                      "delete",
                      "set-password",
                      "get",
                      "update",
                      "impersonate-admins"
                    ],
                    "session": [
                      "list",
                      "revoke",
                      "delete"
                    ],
                    "project": [
                      "read",
                      "manage"
                    ],
                    "validation": [
                      "review",
                      "finalize",
                      "report"
                    ],
                    "app": [
                      "admin-access",
                      "bypass-approval"
                    ],
                    "role": [
                      "manage-sensitive"
                    ]
                  }
                }
              },
              "defaultRole": "user",
              "adminRoles": [
                "admin",
                "superadmin"
              ]
            }
          }
        },
        {
          "name": "generic-oauth",
          "config": {
            "id": "generic-oauth",
            "version": "1.6.0",
            "endpoints": {},
            "options": {
              "config": [
                {
                  "providerId": "scheduler",
                  "clientId": "[REDACTED]",
                  "clientSecret": "[REDACTED]",
                  "pkce": true,
                  "discoveryUrl": "http://localhost:3000/.well-known/openid-configuration",
                  "scopes": [
                    "email",
                    "profile",
                    "offline_access",
                    "openid",
                    "schedule:read"
                  ],
                  "redirectURI": "http://localhost:3010/api/auth/callback/scheduler"
                }
              ]
            },
            "$ERROR_CODES": {
              "INVALID_OAUTH_CONFIGURATION": {
                "code": "INVALID_OAUTH_CONFIGURATION",
                "message": "Invalid OAuth configuration"
              },
              "TOKEN_URL_NOT_FOUND": {
                "code": "TOKEN_URL_NOT_FOUND",
                "message": "Invalid OAuth configuration. Token URL not found."
              },
              "PROVIDER_CONFIG_NOT_FOUND": {
                "code": "PROVIDER_CONFIG_NOT_FOUND",
                "message": "No config found for provider"
              },
              "PROVIDER_ID_REQUIRED": {
                "code": "PROVIDER_ID_REQUIRED",
                "message": "Provider ID is required"
              },
              "INVALID_OAUTH_CONFIG": {
                "code": "INVALID_OAUTH_CONFIG",
                "message": "Invalid OAuth configuration."
              },
              "SESSION_REQUIRED": {
                "code": "SESSION_REQUIRED",
                "message": "Session is required"
              },
              "ISSUER_MISMATCH": {
                "code": "ISSUER_MISMATCH",
                "message": "OAuth issuer mismatch. The authorization server issuer does not match the expected value (RFC 9207)."
              },
              "ISSUER_MISSING": {
                "code": "ISSUER_MISSING",
                "message": "OAuth issuer parameter missing. The authorization server did not include the required iss parameter (RFC 9207)."
              }
            }
          }
        },
        {
          "name": "oauth-provider-client",
          "config": {
            "id": "oauth-provider-client",
            "version": "1.6.0",
            "fetchPlugins": [
              {
                "id": "oauth-provider-signin",
                "name": "oauth-provider-signin",
                "description": "Adds the current page query to oauth requests",
                "hooks": {}
              }
            ],
            "$InferServerPlugin": {}
          }
        },
        {
          "name": "tanstack-start-cookies",
          "config": {
            "id": "tanstack-start-cookies",
            "version": "1.6.0",
            "hooks": {
              "after": [
                {}
              ]
            }
          }
        }
      ]
    }
  }
}
```

### Which area(s) are affected? (Select all that apply)

Backend

### Auth config (if applicable)

```typescript
import { betterAuth } from "better-auth"

const LOCAL_DEV_ORIGINS = [
  'localhost:3000',
  'localhost:3010',
]

export const auth = betterAuth({
  baseURL: {
    allowedHosts: [...LOCAL_DEV_ORIGINS],
    protocol: process.env.NODE_ENV === 'development' ? 'http' : 'https',
  },
});
```

### Additional context

TypeError: Invalid URL
    at new URL (node:internal/url:826:25)
    at C:/Users/jeanf/source/repos/gcf-paie-app/node_modules/.pnpm/better-auth@1.6.0_@opentele_987cc74542654a08bb9a396b1cdafa8a/node_modules/better-auth/dist/plugins/magic-link/index.mjs:67:25
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at internalHandler (file:///C:/Users/jeanf/source/repos/gcf-paie-app/node_modules/.pnpm/better-call@1.3.5_zod@4.3.6/node_modules/better-call/dist/endpoint.mjs:30:20)
    at C:/Users/jeanf/source/repos/gcf-paie-app/node_modules/.pnpm/better-auth@1.6.0_@opentele_987cc74542654a08bb9a396b1cdafa8a/node_modules/better-auth/dist/api/to-auth-endpoints.mjs:73:21
    at Object.serverFn (C:/Users/jeanf/source/repos/gcf-paie-app/src/lib/users.api.ts:306:7)
    at server (C:/Users/jeanf/source/repos/gcf-paie-app/node_modules/.pnpm/@tanstack+start-client-core@1.167.9/node_modules/@tanstack/start-client-core/src/createServerFn.ts:798:24)
    at callNextMiddleware (C:/Users/jeanf/source/repos/gcf-paie-app/node_modules/.pnpm/@tanstack+start-client-core@1.167.9/node_modules/@tanstack/start-client-core/src/createServerFn.ts:289:24)
    at Object.assign.__executeServer (C:/Users/jeanf/source/repos/gcf-paie-app/node_modules/.pnpm/@tanstack+start-client-core@1.167.9/node_modules/@tanstack/start-client-core/src/createServerFn.ts:171:28)
    at C:/Users/jeanf/source/repos/gcf-paie-app/node_modules/.pnpm/@tanstack+start-server-core_902d47834cfd6b4f9c10ffc33b2f1af5/node_modules/@tanstack/start-server-core/src/server-functions-handler.ts:161:16 {
  code: 'ERR_INVALID_URL',
  input: ''

Similar to #8559

Perhaps looking every place this is used could correct a lot of these bugs?

 https://github.com/better-auth/better-auth/blob/52c47517a21600d40a3e82c427409083b4a0a9ec/packages/better-auth/src/plugins/magic-link/index.ts#L231: 

line 231:
`
const realBaseURL = new URL(ctx.context.baseURL);
`

### PR DESCRIPTION
**Pull request by bytaesu**
> [!NOTE]
> Functions like `getProtocolFromRequest` previously assumed a `Request` was always present. However, when using `better-call` without `requireRequest`, calls can be made with headers only. This PR fixes that assumption. 

- Closes #9105

### CODE REVIEW

File: packages/better-auth/src/api/to-auth-endpoints.ts [hunk 1]
```diff
@@ -66,6 +68,38 @@ type UserInputContext = Partial<
...
+/**
+ * Cross-realm-safe Request detection:
+ * Plain `instanceof Request` misses polyfilled or cross-realm Requests.
+ */
+function isRequestLike(value: unknown): value is Request {
+	if (value == null || typeof value !== "object") return false;
+	if (value instanceof Request) return true;
+	if (!(Symbol.toStringTag in value)) return false;
+	return value[Symbol.toStringTag] === "Request";
+}
```
Comment (bytaesu) [inline packages/better-auth/src/api/to-auth-endpoints.ts]: https://github.com/nodejs/undici/blob/main/lib/web/fetch/request.js#L989-L991
