### PR TITLE
fix: prevent static nodejs imports and lazy import for non-nodejs env 

### LINKED ISSUE #3945: Adding telemetry to Better Auth broke support for non-node.js environments
### Is this suited for github?

- [x] Yes, this is suited for github

### To Reproduce

Create a backend project with Cloudflare Workers and Hono and try to run it without Workers support for Node.js.

**Error logs:**
X [ERROR] Build failed with 5 errors:

  X [ERROR] Could not resolve "fs/promises"

      node_modules/better-auth/dist/index.mjs:39:7:
        39 │ import 'fs/promises';
           ╵        ~~~~~~~~~~~~~

    The package "fs/promises" wasn't found on the file system but is built into node.
    - Add the "nodejs_compat" compatibility flag to your project.

  X [ERROR] Could not resolve "path"

      node_modules/better-auth/dist/index.mjs:40:7:
        40 │ import 'path';
           ╵        ~~~~~~

    The package "path" wasn't found on the file system but is built into node.
    - Add the "nodejs_compat" compatibility flag to your project.

  X [ERROR] Could not resolve "fs/promises"

      node_modules/better-auth/dist/shared/better-auth.CCMYns0n.mjs:27:15:
        27 │ import fs from 'fs/promises';
           ╵                ~~~~~~~~~~~~~

    The package "fs/promises" wasn't found on the file system but is built into node.
    - Add the "nodejs_compat" compatibility flag to your project.

  X [ERROR] Could not resolve "path"

      node_modules/better-auth/dist/shared/better-auth.CCMYns0n.mjs:28:17:
        28 │ import path from 'path';
           ╵                  ~~~~~~

    The package "path" wasn't found on the file system but is built into node.
    - Add the "nodejs_compat" compatibility flag to your project.

  X [ERROR] Could not resolve "fs"

      node_modules/better-auth/dist/shared/better-auth.CCMYns0n.mjs:182:39:
        182 │   const { default: fs } = await import('fs');
            ╵                                        ~~~~

    The package "fs" wasn't found on the file system but is built into node.
    - Add the "nodejs_compat" compatibility flag to your project.

### Current vs. Expected behavior

Until v1.3.4, Better Auth worked normally with non-node.js environments. Now with v1.3.5, with the addition of built-in node.js modules to make telemetry work, it's not possible to run it unless adding node.js support to the environment, which isn't possible or desirable in some cases.

### What version of Better Auth are you using?

v1.3.5

### System info

```bash
Framework: Hono
Environment: Cloudflare Workers
```

### Which area(s) are affected? (Select all that apply)

Backend

### Auth config (if applicable)

```typescript

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Kinfe123**
closes #3945

## Summary by cubic
Updated telemetry and package utilities to prevent static Node.js imports and use lazy imports for better runtime compatibility, including support for edge and Cloudflare environments.

- **Bug Fixes**
 - Replaced static imports of Node.js modules with dynamic imports to avoid bundler issues in non-Node runtimes.
 - Improved runtime detection to handle edge environments without Node.js globals.
 - Updated tests to verify initialization in edge-like environments.

### CODE REVIEW

File: packages/better-auth/src/telemetry/detectors/detect-system-info.ts [hunk 1]
```diff
@@ -76,8 +76,9 @@ export async function detectSystemInfo() {
 	try {
 		//check if it's cloudflare
 		if (getVendor() === "cloudflare") return "cloudflare";
-
-		const { default: os } = await import("os");
+		const importRuntime = (m: string) =>
+			(Function("mm", "return import(mm)") as any)(m);
```
Comment (Bekacru) [inline packages/better-auth/src/telemetry/detectors/detect-system-info.ts:80]: I think this isn't required. It should work with try catch already

Comment (Kinfe123) [reply packages/better-auth/src/telemetry/detectors/detect-system-info.ts:80]: This is for lazy loading works with dynamic import.

Comment (Kinfe123) [reply packages/better-auth/src/telemetry/detectors/detect-system-info.ts:80]: this also helps to avoid the litral check on flagging the runtime.
