### PR TITLE
fix: respect `errorCallbackURL` in failed oauth flows

### LINKED ISSUE #1580: `errorCallbackURL` is not working it is ignored on error
### Is this suited for github?

- [x] #1581

### To Reproduce

Image

most probably this is due to callback api route and in my case code is not generated as i cancel the process to choose another account 

logger do print access_denied and error_description=undefined but it do not redirect it 

### Current vs. Expected behavior

Current : 

it is ignoring errorCallbackURL in social signing process even if it is passed and redirecting it to api default error page

expected
it should redirect to the callbackurl passed in social loging 
```typescript
await authClient.signIn.social(
	{
		provider: "google",
		callbackURL: "/dashboard",
		errorCallbackURL: "/sign-in",
	},
	{
		onRequest: () => {
			setIsOAuthLogin(true);
		},
		onError: (ctx) => {
			setIsOAuthLogin(false);
			toast.error(ctx.error.message);
		},
	},
);
``` 
in my case it should redirect it to signing page with queries code and description as designed

### What version of Better Auth are you using?

1.1.21

### Provide environment information

```bash
- OS : Windows
- Browser : Chrome
```

### Which area(s) are affected? (Select all that apply)

Client

### Auth config (if applicable)

```typescript
export const auth = betterAuth({
	appName: "Notespace",
	database: drizzleAdapter(db, {
		provider: "pg",
		schema: {
			...schema,
			user: schema.UserTable,
			account: schema.ConnectedAuthProvidersTable,
			session: schema.UserAuthSessionTable,
			verification: schema.UserAuthVerificationTable,
		},
	}),
	emailAndPassword: {
		enabled: true,
		autoSignIn: true,
		requireEmailVerification: true,
	},
	emailVerification: {
		sendOnSignUp: true,
		autoSignInAfterVerification: true,
		sendVerificationEmail: async ({ user, url }) => {
			await sendEmail({
				to: user.email,
				subject: "Verify your email address",
				text: `Click the link to verify your email: ${url}`,
			});
		},
	},
	socialProviders: {
		google: {
			clientId: process.env.GOOGLE_CLIENT_ID as string,
			clientSecret: process.env.GOOGLE_CLIENT_SECRET as string,
		},
	},
	plugins: [openAPI()],
} satisfies BetterAuthOptions);
```

### Additional context

Images for reference :

Image

Image

### PR DESCRIPTION
**Pull request by frectonz**
closes #1580
    

---

## Summary by cubic
Respect the errorCallbackURL for failed OAuth callbacks so users land on the app’s custom error page. Also forwards error_description when provided.

- **Bug Fixes**
  - Use errorCallbackURL from parsed state for provider errors, missing state, and missing code.
  - Centralize redirects via redirectOnError; builds URLs with URLSearchParams and preserves existing query strings, including error_description.
  - Reorder checks to parse state first so the custom error URL is available; keeps error logging.

### CODE REVIEW

File: packages/better-auth/src/api/routes/callback.ts [hunk 1]
```diff
@@ -43,16 +43,6 @@ export const callbackOAuth = createAuthEndpoint(
 
 		const { code, error, state, error_description, device_id } = queryOrBody;
 
-		if (error) {
-			throw c.redirect(
-				`${defaultErrorURL}?error=${error}&error_description=${error_description}`,
-			);
-		}
-
-		if (!state) {
```
Comment (Bekacru) [inline packages/better-auth/src/api/routes/callback.ts:52]: if there is no state the parse state will fail

Comment (frectonz) [reply packages/better-auth/src/api/routes/callback.ts:52]: fixed

**Comment by frectonz** [comment]
We don't really have a way to test an oauth callback endpoint now, but I will figure something out.
