### PR TITLE
fix(oauth): support case-insensitive email matching for social account linking

### LINKED ISSUE #7806: OAuth account linking fails when email casing differs between provider and existing account
### Is this suited for github?

- [x] Yes, this is suited for github

### To Reproduce

1. Create an account using a standard email/password provider with a lowercase email: johndoe@email.com.
2. Attempt to sign in or link an account via an OAuth provider (e.g., Google or GitHub) where the primary email is returned with capital letters: JohnDoe@email.com.
3. Observe that the linking process fails or creates a duplicate user instead of linking to the existing record.

### Current vs. Expected behavior

Account linking fails during the OAuth flow if the email address returned by the OAuth provider has different casing than the email address already stored in the database.

While the email addresses are logically the same (e.g., johndoe@email.com and JohnDoe@email.com), the system treats them as distinct, preventing the automatic or manual linking of the OAuth identity to the existing user profile.

### What version of Better Auth are you using?

1.4.13

### System info

```bash
{
  "system": {
    "platform": "win32",
    "arch": "x64",
    "version": "Windows 11 Pro",
    "release": "10.0.26200",
    "cpuCount": 12,
    "cpuModel": "AMD Ryzen 5 4600H with Radeon Graphics         ",
    "totalMemory": "31.37 GB",
    "freeMemory": "12.41 GB"
  },
  "node": {
    "version": "v24.13.0",
    "env": "development"
  },
  "packageManager": {
    "name": "npm",
    "version": "11.6.2"
  },
  "frameworks": [
    {
      "name": "next",
      "version": "16.1.5"
    },
    {
      "name": "react",
      "version": "19.1.0"
    }
  ],
  "databases": [
    {
      "name": "pg",
      "version": "^8.17.2"
    },
    {
      "name": "@prisma/client",
      "version": "7.3.0"
    }
  ],
  "betterAuth": {
    "version": "1.4.13",
    "config": null
  }
}
```

### Which area(s) are affected? (Select all that apply)

Backend

### Auth config (if applicable)

```typescript
import { betterAuth } from "better-auth"
export const auth = betterAuth({
  database: prismaAdapter(db, {
    provider: "postgresql",
  }),
  emailAndPassword: {  
    enabled: true
  },
  socialProviders: {
    google: {
      clientId: process.env["AUTH_GOOGLE_ID"] as string,
      clientSecret: process.env["AUTH_GOOGLE_SECRET"] as string,
      disableSignUp: true,
    },
  },
});
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by karuppusamy-d**
This ensures that social account linking succeeds even if the email
returned by the OAuth provider has different casing than the email
currently associated with the user.

- Update `linkSocialAccount` and `callbackOAuth` to use case-insensitive email comparison.
- Added comprehensive tests for both callback and idToken flows.
- Prevents "email_doesn't_match" errors due to case sensitivity.

Closes #7806

---
## Summary by cubic
Make email comparison case-insensitive during social account linking. This prevents mismatches when OAuth providers return different casing, so linking succeeds instead of showing "email_doesn't_match".

- **Bug Fixes**
  - Compare emails case-insensitively in linkSocialAccount, callbackOAuth, and the generic OAuth callback route.
  - Add tests for callback and idToken flows that cover casing differences.

<sup>Written for commit 199d42032f7b55f142a1e40090d5af99fa4f0562. Summary will update on new commits.</sup>

### CODE REVIEW

File: packages/better-auth/src/api/routes/callback.ts [hunk 1]
```diff
@@ -187,7 +187,7 @@ export const callbackOAuth = createAuthEndpoint(
 			}
 
 			if (
-				userInfo.email !== link.email &&
+				userInfo.email?.toLowerCase() !== link.email &&
```
Comment (bytaesu) [inline packages/better-auth/src/api/routes/callback.ts]:
```suggestion
				userInfo.email?.toLowerCase() !== link.email.toLowerCase() &&
```

File: packages/better-auth/src/api/routes/account.ts [hunk 2]
```diff
@@ -309,7 +309,7 @@ export const linkSocialAccount = createAuthEndpoint(
 			}
 
 			if (
-				linkingUserInfo.user.email !== session.user.email &&
+				linkingUserInfo.user.email?.toLowerCase() !== session.user.email &&
```
Comment (bytaesu) [inline packages/better-auth/src/api/routes/account.ts]:
```suggestion
				linkingUserInfo.user.email?.toLowerCase() !== session.user.email.toLowerCase() &&
```

File: packages/better-auth/src/oauth2/link-account.test.ts [hunk 3]
```diff
@@ -231,6 +231,178 @@ describe("oauth2 - email verification on link", async () => {
 	});
 });
 
+describe("oauth2 - account linking with case insensitive email", async () => {
```
Comment (bytaesu) [inline packages/better-auth/src/oauth2/link-account.test.ts:237]: Could you add this comment on the describe block? 🙏
```ts
/**
 * @see https://github.com/better-auth/better-auth/issues/7806
 */
```

**Comment by karuppusamy-d** [comment]
> https://github.com/better-auth/better-auth/blob/canary/packages/better-auth/src/plugins/generic-oauth/routes.ts#L457
> 
> There's one part missing 🙏

Thanks for the ping! I believe userInfo.email is already handled on #L432. Should we still add a manual conversion here as a redundant check, or are we good to leave it as is?

File: packages/better-auth/src/api/routes/callback.ts (hunk 1 above)
Comment (karuppusamy-d) [reply packages/better-auth/src/api/routes/callback.ts]: @bytaesu link.email is already in lowercase as it was from database. should we still add a manual conversion here?

File: packages/better-auth/src/api/routes/account.ts (hunk 2 above)
Comment (karuppusamy-d) [reply packages/better-auth/src/api/routes/account.ts]: @bytaesu session.user.email will be in lowercase as it was from database.

**Comment by bytaesu** [comment]
Hi @karuppusamy-d, thanks for working on this!

I think it's better to compare the two values in lowercase.

---

> https://github.com/better-auth/better-auth/blob/canary/packages/better-auth/src/plugins/generic-oauth/routes.ts#L457

Also, while `link.email` is always lowercase via the internalAdapter, this isn't 100% guaranteed when using the community DB adapter or DB migration, so the issue could reoccur 🤔

what do you think?

**Comment by karuppusamy-d** [comment]
Hi @bytaesu , 

Agreed, handling that edge case now will definitely save some headaches later.

I’ve pushed the update. Thanks for the catch.
