### PR TITLE
fix: chunk account data cookie

### LINKED ISSUE #6379: Next.js server components `getAccessToken` results to `Account Not Found` while client components succeed in stateless mode. (Cognito Provider)
### Is this suited for github?

- [x] Yes, this is suited for github

### To Reproduce

1. Clone the reproduction repository: https://github.com/kenfdev/study-betterauth-nextjs
2. Set up the environment with Cognito provider credentials
3. Configure app/const.ts to use provider = 'cognito'
4. Start the development server with npm run dev
5. Navigate to /login and sign in with Cognito
6. After successful authentication, navigate to /dashboard
7. Observe that auth.api.getAccessToken() fails in the server component

### Current vs. Expected behavior

Current behavior:
- When signing in with Cognito, the better-auth.account_data cookie is not set in the browser
- In server components, auth.api.getAccessToken({ providerId: 'cognito', headers }) fails because the account data is unavailable
- In client components, authClient.getAccessToken({ providerId: 'cognito' }) succeeds (likely because it uses a different code path that doesn't rely on the cookie. not sure though)

Succeeding with github provider

Image

Server components failure with Cognito provider

Image

Expected behavior:
- The better-auth.account_data cookie should be set consistently for all OAuth providers
- getAccessToken() should work the same way in both server and client components

Root cause analysis:
Cognito returns 3 large JWT tokens (accessToken, refreshToken, idToken), which collectively exceed the browser's ~4KB cookie size limit. Example token sizes from my testing:
- accessToken: ~870 chars
- refreshToken: ~1560 chars
- idToken: ~890 chars

This totals ~3320 chars just for the tokens, and after base64/encryption encoding with the other account fields (accountId, providerId, userId, etc.), the cookie value exceeds the 4KB limit
and silently fails to be set.

Google and GitHub providers work probably because their tokens are smaller and fit within the cookie limit.

### What version of Better Auth are you using?

1.4.3

### System info

```bash
{
  "system": {
    "platform": "linux",
    "arch": "x64",
    "version": "#1 SMP PREEMPT_DYNAMIC Thu Jun  5 18:30:46 UTC 2025",
    "release": "6.6.87.2-microsoft-standard-WSL2",
    "cpuCount": 24,
    "cpuModel": "13th Gen Intel(R) Core(TM) i7-13700F",
    "totalMemory": "47.04 GB",
    "freeMemory": "33.16 GB"
  },
  "node": {
    "version": "v20.19.6",
    "env": "development"
  },
  "packageManager": {
    "name": "npm",
    "version": "10.8.2"
  },
  "frameworks": [
    {
      "name": "next",
      "version": "16.0.5"
    },
    {
      "name": "react",
      "version": "19.2.0"
    }
  ],
  "databases": [
    {
      "name": "pg",
      "version": "^8.16.3"
    }
  ],
  "betterAuth": {
    "version": "^1.4.3",
    "config": {
      "logger": {
        "level": "debug",
        "disabled": false,
        "disableColors": false
      },
      "socialProviders": {
        "google": {},
        "github": {},
        "cognito": {}
      },
      "session": {
        "cookieCache": {
          "enabled": true,
          "maxAge": 604800,
          "strategy": "jwe",
          "refreshCache": true
        }
      },
      "account": {
        "updateAccountOnSignIn": true,
        "storeStateStrategy": "cookie",
        "storeAccountCookie": true
      },
      "plugins": []
    }
  }
}
```

### Which area(s) are affected? (Select all that apply)

Backend, Client, Documentation

### Auth config (if applicable)

```typescript
import { betterAuth } from 'better-auth';

export const auth = betterAuth({
  logger: {
    level: 'debug',
    disabled: false,
    disableColors: false,
  },

  // Built-in social providers (commented out - using genericOAuth instead)
  socialProviders: {
    google: {
      clientId: process.env.GOOGLE_CLIENT_ID as string,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET as string,
    },
    github: {
      clientId: process.env.GITHUB_CLIENT_ID as string,
      clientSecret: process.env.GITHUB_CLIENT_SECRET as string,
    },
    cognito: {
      clientId: process.env.COGNITO_CLIENT_ID as string,
      clientSecret: process.env.COGNITO_CLIENT_SECRET as string,
      domain: process.env.COGNITO_DOMAIN as string, // e.g. "your-app.auth.us-east-1.amazoncognito.com"
      region: process.env.COGNITO_REGION as string, // e.g. "us-east-1"
      userPoolId: process.env.COGNITO_USERPOOL_ID as string,
    },
  },

  session: {
    cookieCache: {
      enabled: true,
      maxAge: 7 * 24 * 60 * 60, // 7 days cache duration
      strategy: 'jwe', // can be "jwt" or "compact"
      refreshCache: true, // Enable stateless refresh
    },
  },

  account: {
    updateAccountOnSignIn: true,
    storeStateStrategy: 'cookie',
    storeAccountCookie: true, // Store account data after OAuth flow in a cookie (useful for database-less flows)
  },

  plugins: [],
});
```

### Additional context

Additional context

- Configuration: Using storeAccountCookie: true in account config
- Server component code (app/dashboard/page.tsx:21-26):

```ts
const tokenResponse = await auth.api.getAccessToken({
  body: { providerId: 'cognito' },
  headers: await headers(),
});
```

- Client component code (app/dashboard/dashboard-client.tsx:18-24):

```ts
authClient.getAccessToken({ providerId: 'cognito' })
  .then((res) => {
    setAccessToken(res?.data?.accessToken ?? res?.accessToken ?? null);
  });
```

- The client component call succeeds while the server component call fails, suggesting different underlying mechanisms
- This is probably reproducible locally with any Cognito setup that returns all 3 tokens (though it may not depending on the token size)

### PR DESCRIPTION
**Pull request by jslno**
closes #6379

---
## Summary by cubic
Chunk and JWT-encode the account data cookie with chunking support to prevent truncation and fix unreliable reads. Addresses #6379 by switching endpoints to consistent storage/decoding and cleaning stale chunks.

- **Bug Fixes**
  - Store account data as a JWT payload; chunk when size exceeds ~4KB.
  - Add setAccountCookie and getAccountCookie helpers; use in OAuth link, getAccessToken, refreshToken, and accountInfo.
  - Read account data via getChunkedCookie + symmetricDecodeJWT; clean old chunks when data fits in one cookie.
  - Set a 5-minute maxAge to keep cookie small and short-lived.

<sup>Written for commit 92b24c5a95706a3bd0fb741f3a763e4f0b658b71. Summary will update automatically on new commits.</sup>

### CODE REVIEW

File: packages/better-auth/src/api/routes/account.ts [hunk 1]
```diff
@@ -709,13 +713,16 @@ export const refreshToken = createAuthEndpoint(
...
+		const accountDataCookie = getChunkedCookie(ctx, accountDataCookieName);
 		let account: Account | undefined = undefined;
 		const accountData = accountDataCookie
-			? safeJSONParse<Account>(accountDataCookie)
+			? safeJSONParse<Account>(
+					await symmetricDecodeJWT(
+						accountDataCookie,
+						ctx.context.secret,
+						"better-auth-account",
+					),
```
Comment (Bekacru) [inline packages/better-auth/src/api/routes/account.ts]: I think we should have `getAccountCookie` helper that also does the decode jwt
