### PR TITLE
fix(expo): fix cookie-based OAuth state with expo-authorization-proxy

### LINKED ISSUE #6847: Expo + stateless (v1.4): OAuth callback fails with State Mismatch and redirects to error=please_restart_the_process (Keycloak/genericOAuth)
### Is this suited for github?

- [x] Yes, this is suited for github

### To Reproduce

1. Create an Expo app using **Expo Router API routes**.
2. Configure Better Auth **v1.4+** with:
   - `storeStateStrategy: "cookie"`
   - Stateless sessions via `session.cookieCache`
   - `expo()` plugin
   - `genericOAuth` with **Keycloak**
3. Configure the Expo client with:
   - `createAuthClient`
   - `expoClient(...)`
   - `genericOAuthClient()`
4. Run the app on **Android (Expo / Zebra device)** and trigger login via:
   ```ts
   authClient.signIn.oauth2({
              providerId: 'keycloak',
              callbackURL: '/',
            })
   ```

> Note:  
> The same setup works correctly when accessing the app **via the browser (web)**, but fails **only when login is initiated from the native app**.

## Current Behavior

After returning from Keycloak, the OAuth callback fails with:

```
ERROR [Better Auth]: State Mismatch. OAuth state cookie not found
```

and redirects to:

```
/api/auth/error?error=please_restart_the_process
```

This happens **even though the OAuth `state` cookie is present on the callback request** and the `state` query parameter matches the cookie prefix.

### Observed behavior from logs

During a single native login attempt, the following occurs:

1. **POST** `/api/auth/sign-in/oauth2`
   - Cookie present:
     ```
     better-auth.oauth_state=...
     ```
   - Server sets:
     ```
     Set-Cookie: better-auth.oauth_state=...
     ```

2. **GET** `/api/auth/expo-authorization-proxy`
   - No cookies (expected)
   - Server sets:
     ```
     Set-Cookie: better-auth.state=<state>.<signature>
     ```

3. **GET** `/api/auth/oauth2/callback/keycloak?state=<state>`
   - Cookie present:
     ```
     better-auth.state=<state>.<signature>
     ```
   - Server logs:
     ```
     State Mismatch. OAuth state cookie not found
     ```

This shows that **two different cookie names are used during the same OAuth flow**:

- `better-auth.oauth_state` (cookie-based state strategy)
- `better-auth.state` (default/db-style state strategy)

Because of this, the callback validation fails and triggers `please_restart_the_process`.

---

## Expected Behavior

When `storeStateStrategy: "cookie"` is configured:

- The OAuth state should be stored **consistently under one cookie name** for the entire flow.
- The cookie set before redirect should be the same cookie read during the callback.
- The callback should succeed when:
  - the `state` query parameter matches the cookie prefix
  - the cookie is present and valid

The native (Expo) OAuth flow should behave the same as the web flow.

### What version of Better Auth are you using?

1.4.7

### System info

```bash
{
  "system": {
    "platform": "linux",
    "arch": "x64",
    "version": "#1 SMP PREEMPT_DYNAMIC Thu Jun  5 18:30:46 UTC 2025",
    "release": "6.6.87.2-microsoft-standard-WSL2",
    "cpuCount": 8,
    "cpuModel": "11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz",
    "totalMemory": "11.68 GB",
    "freeMemory": "6.78 GB"
  },
  "node": {
    "version": "v22.12.0",
    "env": "development"
  },
  "packageManager": {
    "name": "npm",
    "version": "11.7.0"
  },
  "frameworks": [
    {
      "name": "react",
      "version": "19.1.4"
    }
  ],
  "databases": null,
  "betterAuth": {
    "version": "1.4.7",
    "config": {
      "plugins": [
        {
          "name": "expo",
          "config": {
            "id": "expo",
            "hooks": {
              "after": [
                {}
              ]
            },
            "endpoints": {}
          }
        },
        {
          "name": "generic-oauth",
          "config": {
            "id": "generic-oauth",
            "endpoints": {},
            "$ERROR_CODES": {
              "INVALID_OAUTH_CONFIGURATION": "Invalid OAuth configuration",
              "TOKEN_URL_NOT_FOUND": "Invalid OAuth configuration. Token URL not found.",
              "PROVIDER_CONFIG_NOT_FOUND": "No config found for provider",
              "PROVIDER_ID_REQUIRED": "Provider ID is required",
              "INVALID_OAUTH_CONFIG": "Invalid OAuth configuration.",
              "SESSION_REQUIRED": "Session is required"
            }
          }
        }
      ],
      "trustedOrigins": [
        "com.company.app://"
      ],
      "session": {
        "cookieCache": {
          "enabled": true,
          "maxAge": 7200,
          "strategy": "jwt",
          "refreshCache": false
        }
      },
      "account": {
        "storeStateStrategy": "cookie",
        "storeAccountCookie": true,
        "skipStateCookieCheck": true
      }
    }
  }
}
```

### Which area(s) are affected? (Select all that apply)

Backend, Client

### Auth config (if applicable)

```typescript
import 'server-only'
import { betterAuth } from 'better-auth'
import { genericOAuth, keycloak } from 'better-auth/plugins'
import { expo } from '@better-auth/expo'

export const auth = betterAuth({
  plugins: [
    expo(),
    genericOAuth({
      config: [
        keycloak({
          clientId: process.env.KEYCLOAK_CLIENT_ID!,
          clientSecret: process.env.KEYCLOAK_CLIENT_SECRET!,
          issuer: process.env.KEYCLOAK_ISSUER!,
          scopes: ['openid', 'profile', 'email'],
          pkce: true,
        }),
      ],
    }),
  ],
  trustedOrigins: [
    'com.company.app://',
    // Development mode - Expo's exp:// scheme with local IP ranges
    ...(process.env.NODE_ENV === 'development'
      ? [
          'exp://*/*', // Trust all Expo development URLs
          'exp://10.0.0.*:*/*', // Trust 10.0.0.x IP range
          'exp://192.168.*.*:*/*', // Trust 192.168.x.x IP range
          'exp://172.*.*.*:*/*', // Trust 172.x.x.x IP range
          'exp://localhost:*/*', // Trust localhost
        ]
      : []),
  ],
  session: {
    cookieCache: {
      enabled: true,
      maxAge: 60 * 60 * 2, // 2 hours
      strategy: 'jwt',
      refreshCache: false,
    },
  },
  account: {
    storeStateStrategy: 'cookie',
    storeAccountCookie: true,
    skipStateCookieCheck: true,
  },
})
```

### Additional context

- This issue occurs **only in the native Expo flow** using:
  - `expo()` plugin
  - `/api/auth/expo-authorization-proxy`
- The same configuration works correctly when logging in via the browser (web).
- Logs suggest that:
  - the Expo authorization proxy sets a `better-auth.state` cookie
  - while the app-initiated OAuth flow uses `better-auth.oauth_state`
- This appears related to the **new stateless / cookie-based state handling introduced in v1.4**.
- Secondary storage and `skipStateCookieCheck` do not resolve the issue.
- The error always ends in:
  ```
  /api/auth/error?error=please_restart_the_process
  ```

## Debug instrumentation used

To verify cookies and `Set-Cookie` behavior in the Expo Router API route, I temporarily replaced the handler export with this logging wrapper:

```ts
// app/api/auth/[...auth]+api.ts
import { auth } from "@/server/auth";

// Keep logs readable and avoid leaking unrelated cookies.
function extractBetterAuthCookies(cookieHeader: string | null) {
  if (!cookieHeader) return {};
  const out: Record<string, string> = {};
  for (const part of cookieHeader.split(/;\s*/)) {
    const i = part.indexOf("=");
    if (i === -1) continue;
    const name = part.slice(0, i).trim();
    const value = part.slice(i + 1);
    if (name.startsWith("better-auth.")) out[name] = value;
  }
  return out;
}

async function handle(req: Request) {
  const url = new URL(req.url);
  const cookie = req.headers.get("cookie");

  console.log("=== BetterAuth API Route ===");
  console.log("Method:", req.method);
  console.log("Request URL:", url.toString());
  console.log("Cookie header:", cookie);
  console.log("BetterAuth cookies:", extractBetterAuthCookies(cookie));

  const res = await auth.handler(req);

  const setCookie = res.headers.get("set-cookie");
  if (setCookie) {
    console.log("Set-Cookie header:", setCookie);

    const names = setCookie
      .split(/,(?=\\s*[^;]+=)/)
      .map((c) => c.split(";", 1)[0])
      .map((kv) => kv.split("=", 1)[0]?.trim())
      .filter(Boolean);
    console.log("Set-Cookie names:", names);
  } else {
    console.log("Set-Cookie header: <none>");
  }

  console.log("============================");

  return res;
}

export async function GET(req: Request) {
  return handle(req);
}

export async function POST(req: Request) {
  return handle(req);
}
```

### Full logs

<details>
  <summary>Click to expand full logs</summary>

```txt
Android Bundled 411ms node_modules/expo-network/build/Network.js (613 modules)
RSC(Web) Bundled 960ms src/app/api/auth/[...auth]+api.ts (640 modules)
=== BetterAuth API Route ===
Method: GET
Request URL: http://localhost:8081/api/auth/get-session
Cookie header: ; better-auth.oauth_state=f0918ac00f4ca8d06e66e6e92324c36dd65095737e18c2e0c8a86ad9e1603c6cce1343865ffeb52e65803d1f160ad9a7c9d00cdf9ba1da3c5598a6dfc66ed3fc8538cff767363f2c803703a5e937b649f3575a461f21e7fb761dad9c9df64e192cd0f1687f7b72dfd033f28daa7af72712e72876e50fb17a86b15bc8a2b81d81c451e33175b26bd7ad0ba81323e52c7fad1679796f57a392eb899bf2b3ce519500de76ed2d09d6ea9979c9ba85472536754fde415a4c586c05d937b01d8593cc2335ba88fd9f287f062b249dc604a53bf3ea8559bc6dccb4e695d30f657188a1a125fc54d3f3e678041a417ffbc40397911e1626f4441e1d1cfb13170b9ce4b6d45e1f084142c58c8eab13eae0a6d86254f77d8d64eeb4b28f04960dbf72b91c0859afaa0b27975e2de82408e0fff64c
BetterAuth cookies: {
  'better-auth.oauth_state': 'f0918ac00f4ca8d06e66e6e92324c36dd65095737e18c2e0c8a86ad9e1603c6cce1343865ffeb52e65803d1f160ad9a7c9d00cdf9ba1da3c5598a6dfc66ed3fc8538cff767363f2c803703a5e937b649f3575a461f21e7fb761dad9c9df64e192cd0f1687f7b72dfd033f28daa7af72712e72876e50fb17a86b15bc8a2b81d81c451e33175b26bd7ad0ba81323e52c7fad1679796f57a392eb899bf2b3ce519500de76ed2d09d6ea9979c9ba85472536754fde415a4c586c05d937b01d8593cc2335ba88fd9f287f062b249dc604a53bf3ea8559bc6dccb4e695d30f657188a1a125fc54d3f3e678041a417ffbc40397911e1626f4441e1d1cfb13170b9ce4b6d45e1f084142c58c8eab13eae0a6d86254f77d8d64eeb4b28f04960dbf72b91c0859afaa0b27975e2de82408e0fff64c'
}
Set-Cookie header: <none>
============================
=== BetterAuth API Route ===
Method: POST
Request URL: http://localhost:8081/api/auth/sign-in/oauth2
Cookie header: ; better-auth.oauth_state=f0918ac00f4ca8d06e66e6e92324c36dd65095737e18c2e0c8a86ad9e1603c6cce1343865ffeb52e65803d1f160ad9a7c9d00cdf9ba1da3c5598a6dfc66ed3fc8538cff767363f2c803703a5e937b649f3575a461f21e7fb761dad9c9df64e192cd0f1687f7b72dfd033f28daa7af72712e72876e50fb17a86b15bc8a2b81d81c451e33175b26bd7ad0ba81323e52c7fad1679796f57a392eb899bf2b3ce519500de76ed2d09d6ea9979c9ba85472536754fde415a4c586c05d937b01d8593cc2335ba88fd9f287f062b249dc604a53bf3ea8559bc6dccb4e695d30f657188a1a125fc54d3f3e678041a417ffbc40397911e1626f4441e1d1cfb13170b9ce4b6d45e1f084142c58c8eab13eae0a6d86254f77d8d64eeb4b28f04960dbf72b91c0859afaa0b27975e2de82408e0fff64c
BetterAuth cookies: {
  'better-auth.oauth_state': 'f0918ac00f4ca8d06e66e6e92324c36dd65095737e18c2e0c8a86ad9e1603c6cce1343865ffeb52e65803d1f160ad9a7c9d00cdf9ba1da3c5598a6dfc66ed3fc8538cff767363f2c803703a5e937b649f3575a461f21e7fb761dad9c9df64e192cd0f1687f7b72dfd033f28daa7af72712e72876e50fb17a86b15bc8a2b81d81c451e33175b26bd7ad0ba81323e52c7fad1679796f57a392eb899bf2b3ce519500de76ed2d09d6ea9979c9ba85472536754fde415a4c586c05d937b01d8593cc2335ba88fd9f287f062b249dc604a53bf3ea8559bc6dccb4e695d30f657188a1a125fc54d3f3e678041a417ffbc40397911e1626f4441e1d1cfb13170b9ce4b6d45e1f084142c58c8eab13eae0a6d86254f77d8d64eeb4b28f04960dbf72b91c0859afaa0b27975e2de82408e0fff64c'
}
Set-Cookie header: better-auth.oauth_state=d625a78b896552eaf9045e63cc4a0dc7a248025bd1adc77e872e3cfabc919f958435c3a1aefc11481cb1bf96cef0cae15851362576356c4f695b35c218bf9485dc2ea712b9f7f2ce4328ff8ca012fe3d720cecb0031df0644dbdc786fdd4c53131cb926c11f6b58362c87ebcd72737ba81792c3a2e2874d81138cff04f8ae2df7bdd2be7b95f98411dfa996ac7cc7f886ec080fbe8811bdb24e8d3967bba63d4a9dc4c07cffec72e2d12f598c8ada6fb6fc75b2bf8dfb6d58c724f839c644b4d9ffd6e0a0e613235b2ea12dda2ce607103a0a5310940990f7ca25a6b3a75291da01e8b6857463b4718e1493685d6772c3fd8d3d06c5fa02db963540ad7e1ffa42879ca6ebd943d5be4a9c910cf031c375069ebea30b9c6b765287efa7945b24a06029c49a70bd0c3b38a926adc3b1663; Max-Age=600000; Path=/; HttpOnly; SameSite=Lax
Set-Cookie names: [ 'better-auth.oauth_state' ]
============================
Android Bundled 468ms node_modules/expo-web-browser/build/WebBrowser.js (613 modules)
=== BetterAuth API Route ===
Method: GET
Request URL: http://localhost:8081/api/auth/get-session
Cookie header: ; better-auth.oauth_state=d625a78b896552eaf9045e63cc4a0dc7a248025bd1adc77e872e3cfabc919f958435c3a1aefc11481cb1bf96cef0cae15851362576356c4f695b35c218bf9485dc2ea712b9f7f2ce4328ff8ca012fe3d720cecb0031df0644dbdc786fdd4c53131cb926c11f6b58362c87ebcd72737ba81792c3a2e2874d81138cff04f8ae2df7bdd2be7b95f98411dfa996ac7cc7f886ec080fbe8811bdb24e8d3967bba63d4a9dc4c07cffec72e2d12f598c8ada6fb6fc75b2bf8dfb6d58c724f839c644b4d9ffd6e0a0e613235b2ea12dda2ce607103a0a5310940990f7ca25a6b3a75291da01e8b6857463b4718e1493685d6772c3fd8d3d06c5fa02db963540ad7e1ffa42879ca6ebd943d5be4a9c910cf031c375069ebea30b9c6b765287efa7945b24a06029c49a70bd0c3b38a926adc3b1663
BetterAuth cookies: {
  'better-auth.oauth_state': 'd625a78b896552eaf9045e63cc4a0dc7a248025bd1adc77e872e3cfabc919f958435c3a1aefc11481cb1bf96cef0cae15851362576356c4f695b35c218bf9485dc2ea712b9f7f2ce4328ff8ca012fe3d720cecb0031df0644dbdc786fdd4c53131cb926c11f6b58362c87ebcd72737ba81792c3a2e2874d81138cff04f8ae2df7bdd2be7b95f98411dfa996ac7cc7f886ec080fbe8811bdb24e8d3967bba63d4a9dc4c07cffec72e2d12f598c8ada6fb6fc75b2bf8dfb6d58c724f839c644b4d9ffd6e0a0e613235b2ea12dda2ce607103a0a5310940990f7ca25a6b3a75291da01e8b6857463b4718e1493685d6772c3fd8d3d06c5fa02db963540ad7e1ffa42879ca6ebd943d5be4a9c910cf031c375069ebea30b9c6b765287efa7945b24a06029c49a70bd0c3b38a926adc3b1663'
}
Set-Cookie header: <none>
============================
=== BetterAuth API Route ===
Method: GET
Request URL: http://localhost:8081/api/auth/expo-authorization-proxy?authorizationURL=https%3A%2F%2Fkeycloak.ilogistics.at%2Fauth%2Frealms%2Fse%2Fprotocol%2Fopenid-connect%2Fauth%3Fresponse_type%3Dcode%26client_id%3Dmobile-ilogistics-expo%26state%3Dju2A8oxZi3EPQt9WPdutU38OX5lhS7kk%26scope%3Dopenid%2Bprofile%2Bemail%26redirect_uri%3Dhttp%253A%252F%252Flocalhost%253A8081%252Fapi%252Fauth%252Foauth2%252Fcallback%252Fkeycloak%26code_challenge_method%3DS256%26code_challenge%3D6WAEqFMVHrYeO5zLlrRTRifu7DRNV0wvT8uhT-gnvbg
Cookie header: null
BetterAuth cookies: {}
Set-Cookie header: better-auth.state=ju2A8oxZi3EPQt9WPdutU38OX5lhS7kk.xggsHckhUqZo%2B%2B6jX9lBembbg%2FNuVlQxZSp3FaZViso%3D; Max-Age=300000; Path=/; HttpOnly; SameSite=Lax
Set-Cookie names: [ 'better-auth.state' ]
============================
=== BetterAuth API Route ===
2025-12-18T07:05:51.908Z ERROR [Better Auth]: State Mismatch. OAuth state cookie not found { state: 'ju2A8oxZi3EPQt9WPdutU38OX5lhS7kk' }
Method: GET
Request URL: http://localhost:8081/api/auth/oauth2/callback/keycloak?state=ju2A8oxZi3EPQt9WPdutU38OX5lhS7kk&session_state=686a7366-f787-48ef-8a5b-d75fd1224437&iss=https%3A%2F%2Fkeycloak.ilogistics.at%2Fauth%2Frealms%2Fse&code=0f603b1a-3677-4f00-9181-37c03e5e3066.686a7366-f787-48ef-8a5b-d75fd1224437.4c9fcf16-e1e3-4936-a511-298d877cd55f
Cookie header: better-auth.state=ju2A8oxZi3EPQt9WPdutU38OX5lhS7kk.xggsHckhUqZo%2B%2B6jX9lBembbg%2FNuVlQxZSp3FaZViso%3D
BetterAuth cookies: {
  'better-auth.state': 'ju2A8oxZi3EPQt9WPdutU38OX5lhS7kk.xggsHckhUqZo%2B%2B6jX9lBembbg%2FNuVlQxZSp3FaZViso%3D'
}
Set-Cookie header: <none>
============================
=== BetterAuth API Route ===
Method: GET
Request URL: http://localhost:8081/api/auth/error?error=please_restart_the_process
Cookie header: better-auth.state=ju2A8oxZi3EPQt9WPdutU38OX5lhS7kk.xggsHckhUqZo%2B%2B6jX9lBembbg%2FNuVlQxZSp3FaZViso%3D
BetterAuth cookies: {
  'better-auth.state': 'ju2A8oxZi3EPQt9WPdutU38OX5lhS7kk.xggsHckhUqZo%2B%2B6jX9lBembbg%2FNuVlQxZSp3FaZViso%3D'
}
Set-Cookie header: <none>
============================
=== BetterAuth API Route ===
Method: GET
Request URL: http://localhost:8081/api/auth/get-session
Cookie header: ; better-auth.oauth_state=d625a78b896552eaf9045e63cc4a0dc7a248025bd1adc77e872e3cfabc919f958435c3a1aefc11481cb1bf96cef0cae15851362576356c4f695b35c218bf9485dc2ea712b9f7f2ce4328ff8ca012fe3d720cecb0031df0644dbdc786fdd4c53131cb926c11f6b58362c87ebcd72737ba81792c3a2e2874d81138cff04f8ae2df7bdd2be7b95f98411dfa996ac7cc7f886ec080fbe8811bdb24e8d3967bba63d4a9dc4c07cffec72e2d12f598c8ada6fb6fc75b2bf8dfb6d58c724f839c644b4d9ffd6e0a0e613235b2ea12dda2ce607103a0a5310940990f7ca25a6b3a75291da01e8b6857463b4718e1493685d6772c3fd8d3d06c5fa02db963540ad7e1ffa42879ca6ebd943d5be4a9c910cf031c375069ebea30b9c6b765287efa7945b24a06029c49a70bd0c3b38a926adc3b1663
BetterAuth cookies: {
  'better-auth.oauth_state': 'd625a78b896552eaf9045e63cc4a0dc7a248025bd1adc77e872e3cfabc919f958435c3a1aefc11481cb1bf96cef0cae15851362576356c4f695b35c218bf9485dc2ea712b9f7f2ce4328ff8ca012fe3d720cecb0031df0644dbdc786fdd4c53131cb926c11f6b58362c87ebcd72737ba81792c3a2e2874d81138cff04f8ae2df7bdd2be7b95f98411dfa996ac7cc7f886ec080fbe8811bdb24e8d3967bba63d4a9dc4c07cffec72e2d12f598c8ada6fb6fc75b2bf8dfb6d58c724f839c644b4d9ffd6e0a0e613235b2ea12dda2ce607103a0a5310940990f7ca25a6b3a75291da01e8b6857463b4718e1493685d6772c3fd8d3d06c5fa02db963540ad7e1ffa42879ca6ebd943d5be4a9c910cf031c375069ebea30b9c6b765287efa7945b24a06029c49a70bd0c3b38a926adc3b1663'
}
Set-Cookie header: <none>
============================
=== BetterAuth API Route ===
Method: GET
Request URL: http://localhost:8081/api/auth/get-session
Cookie header: ; better-auth.oauth_state=d625a78b896552eaf9045e63cc4a0dc7a248025bd1adc77e872e3cfabc919f958435c3a1aefc11481cb1bf96cef0cae15851362576356c4f695b35c218bf9485dc2ea712b9f7f2ce4328ff8ca012fe3d720cecb0031df0644dbdc786fdd4c53131cb926c11f6b58362c87ebcd72737ba81792c3a2e2874d81138cff04f8ae2df7bdd2be7b95f98411dfa996ac7cc7f886ec080fbe8811bdb24e8d3967bba63d4a9dc4c07cffec72e2d12f598c8ada6fb6fc75b2bf8dfb6d58c724f839c644b4d9ffd6e0a0e613235b2ea12dda2ce607103a0a5310940990f7ca25a6b3a75291da01e8b6857463b4718e1493685d6772c3fd8d3d06c5fa02db963540ad7e1ffa42879ca6ebd943d5be4a9c910cf031c375069ebea30b9c6b765287efa7945b24a06029c49a70bd0c3b38a926adc3b1663
BetterAuth cookies: {
  'better-auth.oauth_state': 'd625a78b896552eaf9045e63cc4a0dc7a248025bd1adc77e872e3cfabc919f958435c3a1aefc11481cb1bf96cef0cae15851362576356c4f695b35c218bf9485dc2ea712b9f7f2ce4328ff8ca012fe3d720cecb0031df0644dbdc786fdd4c53131cb926c11f6b58362c87ebcd72737ba81792c3a2e2874d81138cff04f8ae2df7bdd2be7b95f98411dfa996ac7cc7f886ec080fbe8811bdb24e8d3967bba63d4a9dc4c07cffec72e2d12f598c8ada6fb6fc75b2bf8dfb6d58c724f839c644b4d9ffd6e0a0e613235b2ea12dda2ce607103a0a5310940990f7ca25a6b3a75291da01e8b6857463b4718e1493685d6772c3fd8d3d06c5fa02db963540ad7e1ffa42879ca6ebd943d5be4a9c910cf031c375069ebea30b9c6b765287efa7945b24a06029c49a70bd0c3b38a926adc3b1663'
}
Set-Cookie header: <none>
============================
› Stopped server
```

</details>

### PR DESCRIPTION
**Pull request by ruff-exec**
## Summary

This PR fixes Expo native OAuth flows when `storeStateStrategy: "cookie"` is enabled.

In the Expo flow, the `/expo-authorization-proxy` step runs in the system browser and did not have access to the encrypted `better-auth.oauth_state` cookie created during `/sign-in/*`. As a result, the OAuth callback failed with `State Mismatch. OAuth state cookie not found`.

### Expo proxy route (`packages/expo/src/routes.ts`)

- Added an optional `oauthState` query param to `/expo-authorization-proxy`.
- When provided, the proxy sets the `oauth_state` auth cookie (`better-auth.oauth_state` / `__Secure-better-auth.oauth_state`) with a 10 minute TTL (matching core), then redirects to the provider `authorizationURL`.
- If not provided, the proxy preserves the existing behavior (signed `state` cookie derived from the provider authorization URL).

### Expo client (`packages/expo/src/client.ts`)

- Extracts the stored `oauth_state` cookie value from the Expo cookie jar and appends it to the proxy URL as `oauthState=...` when present.
- This bridges the native-stored cookie into the system browser context so the callback can successfully read and decrypt `oauth_state`.

### Tests

- Added a regression test to ensure the proxy URL passed to `openAuthSessionAsync()` includes `oauthState=` when `storeStateStrategy` is configured as `"cookie"`.

## Context / Background

Core Better Auth’s cookie-based OAuth state strategy stores the full state payload (incl. PKCE verifier) in an encrypted `oauth_state` cookie and the callback handler requires it to be present. Expo’s system browser navigation cannot include custom request headers, so the cookie must be set within the browser context before redirecting to the provider.

## Breaking changes / Deprecations

- None. Existing behavior is preserved when `oauthState` is not provided.

## UI changes / Screenshots

- None.

## Related

Closes #6847

---
## Summary by cubic
Fixes Expo OAuth when using cookie-based state by forwarding the encrypted oauth_state to the system browser via the authorization proxy. Prevents “State Mismatch. OAuth state cookie not found” during native sign-in.

- **Bug Fixes**
  - Client reads oauth_state from the Expo cookie jar and adds it as oauthState to the proxy URL.
  - Proxy sets the oauth_state cookie with a 10-minute TTL, then redirects to the provider.
  - For database strategy, the proxy URL omits oauthState; tests cover both strategies.

<sup>Written for commit 1c47c9cf84f306e3d488fd46f4c4781bd3653ff6. Summary will update on new commits.</sup>

### CODE REVIEW

File: packages/expo/src/client.ts [hunk 1]
```diff
@@ -390,7 +421,17 @@ export const expoClient = (opts: ExpoClientOptions) => {
...
 							}
 
-							const proxyURL = `${context.request.baseURL}/expo-authorization-proxy?authorizationURL=${encodeURIComponent(signInURL)}`;
+							const storedCookieJson = await storage.getItem(cookieName);
+							const oauthStateValue = getOAuthStateValue(
+								storedCookieJson,
+								cookiePrefix,
+							);
+							let proxyURL =
+								`${context.request.baseURL}/expo-authorization-proxy` +
```
Comment (himself65) [inline packages/expo/src/client.ts]: Can we please use URLparams here?

Comment (ruff-exec) [reply packages/expo/src/client.ts]: @himself65 For both, because the encodeURIComponent for the authorizationURL was there before?

Comment (himself65) [reply packages/expo/src/client.ts]: https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams

Im talking about this class that automatically handles the url encode

Comment (ruff-exec) [reply packages/expo/src/client.ts]: > https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams
> 
> Im talking about this class that automatically handles the url encode

Ok I see, done

Comment (ruff-exec) [reply packages/expo/src/client.ts]: @himself65 What we also need to consider is:

- I’m getting this warning:
  > `WARN  Value being stored in SecureStore is larger than 2048 bytes and it may not be stored successfully. In a future SDK version, this call may throw an error.`

- The flow **works on Android** for me, but from what I’ve read this is **more of an iOS limitation** (SecureStore/Keychain item size).

**Question:** should we handle this by **chunking**?

- If you’re using **stateless mode**, one workaround is switching the Expo client storage to **AsyncStorage** (it supports larger values), instead of SecureStore.
- However, that doesn’t fully solve the underlying issue, because we can hit size limits on the *cookie side* as well. Per **RFC 6265**, user agents are expected to support **at least 4096 bytes per cookie**, so larger cookie payloads may require **chunking** anyway.

So in general, **chunking for the `oauth_state` cookie** (and potentially for how we persist cookies client-side) seems like the most robust long-term approach.

What do you think?

Comment (Bekacru) [reply packages/expo/src/client.ts]: Yeah chunking both for cookies and secure store make sense cc @himself65

Comment (ruff-exec) [reply packages/expo/src/client.ts]: > Yeah chunking both for cookies and secure store make sense cc @himself65

@Bekacru Maybe this can be done in another PR and this be merged for now, so this issue is fixed and then it can be improved afterwards. If you want I can submit another PR after this one where the chunking is handled and can be further discussed

Comment (ruff-exec) [reply packages/expo/src/client.ts]: @himself65 Is this ok like this? Can this be merged?

**Comment by ruff-exec** [comment]
@himself65 Pls review again

**Comment by kylealwyn** [comment]
following. would be great to get this across the finish line. happy to help in any way!

**Comment by ruff-exec** [comment]
@bytaesu I have updated the test accordingly. Does this fit your requirements?

> Hello @ruff-exec,
> 
> Thanks for working on this 🙂
> 
> I'd like the test to fully reproduce the issue so it can prevent future regressions. In other words, the test should fail with the pre-fix code and accurately reflect the scenario addressed in this PR.
> 
> The current test only checks whether the query string exists, but it would be better to reproduce the actual OAuth flow. A query string may be present even if the login fails.
> 
> Would you be able to work on this?

**Comment by bytaesu** [comment]
@himself65 coud you review this?

**Review by himself65 — APPROVED** [review]

**Comment by bytaesu** [comment]
> Maybe this can be done in another PR and this be merged for now, so this issue is fixed and then it can be improved afterwards. If you want I can submit another PR after this one where the chunking is handled and can be further discussed

Hi @ruff-exec,

Thanks for working on this! Feel free to open the PR 😊

**Comment by ruff-exec** [comment]
Hey @bytaesu, I think this created a new issue in the latest release as when I upgrade from the continuous release of the commit [f4a9f15](https://github.com/better-auth/better-auth/pull/6933/commits/f4a9f15c3f446f971bc34a51fdb42fbcde4dd2b6) to the latest version or even just to the next continuous release  of the 3 commits you made afterwards I get:

```
 ERROR  [TypeError: Cannot read property 'fromJSONSchema' of undefined] 

Code: auth-client.ts
  2 | import { genericOAuthClient } from 'better-auth/client/plugins'
  3 | import { createAuthClient } from 'better-auth/react'
> 4 | import { expoClient } from '@better-auth/expo/client'
    | ^
  5 |
  6 | export const authClient = createAuthClient({
  7 |   baseURL: 'http://localhost:8081',
Call Stack
  <global> (src/client/auth/auth-client.ts:4)
  <global> (src/app/(authenticated)/index.tsx:4)
```

Maybe you can look into this. I don't know wich of the 3 commits you made raises this issue but one of the has to be.
