### PR TITLE
fix: magic link URL construction

### LINKED ISSUE #3759: baseUrl overwritten by path for magic links
### Is this suited for github?

- [x] Yes, this is suited for github

### To Reproduce

I have a basic auth setup

```ts
import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { db } from "../db";
import { magicLink, oAuthProxy, openAPI } from "better-auth/plugins";
import { config } from "@/lib/config";

export const auth = betterAuth({
  basePath: "/",
  database: drizzleAdapter(db, {
    provider: "pg",
  }),
  secret: config.betterAuthSecret,
  baseURL: config.betterAuthUrl,
  trustedOrigins: [config.clientUrl],
  emailAndPassword: {
    enabled: true,
  },
  session: {
    expiresIn: 60 * 60 * 24 * 7,
    updateAge: 60 * 60 * 24,
    cookieCache: {
      enabled: true,
      maxAge: 60 * 5,
    },
  },
  advanced: {
    crossSubDomainCookies: {
      enabled: true,
    },
  },
  security: {
    csrf: {
      disabled: true,
    },
  },
  plugins: [
    openAPI(),
    magicLink({
      expiresIn: 60 * 60, // 1 hour
      rateLimit: {
        window: 60, // 1 minute
        max: 5, // 5 requests per minute
      },

      storeToken: "hashed", // Store tokens as hashed in the database
      sendMagicLink: async ({ email, url }) => {
        console.log("Magic link sent to:", email);
        console.log("Magic link URL:", url);
      },
    }),
    oAuthProxy({
      productionURL: config.clientUrl,
      currentURL: config.betterAuthUrl,
    }),
  ],
  emailVerification: {
    sendOnSignUp: true,
    autoSignInAfterVerification: true,

    sendVerificationEmail: async ({ user, url }) => {
      console.log("Email verification link:", url, user.email);
    },
    afterEmailVerification: async (user, request) => {
      console.log("Email verified for user:", user.email);
    },
  },
});
```

I am seeing verify links that look like this without my base URL
`http://magic-link/verify?token=oqQzaxMarTdUQWNmsFenBMXPwMdZPHIh`

Digging into the magic link code, I can see it's dropping my `host`

Image

`realBaseUrl` has my `host`, `url` does not

Image

___

I would expect `url` to be both host and port aware and not simply using `path`

### Current vs. Expected behavior

`url` should not drop `host` and `port`

### What version of Better Auth are you using?

1.3.4

### Provide environment information

```bash
- OS: OSX 15.5
- Chrome 138.0.7204.169 (
```

### Which area(s) are affected? (Select all that apply)

Backend

### Auth config (if applicable)

```typescript
import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { db } from "../db";
import { magicLink, oAuthProxy, openAPI } from "better-auth/plugins";
import { config } from "@/lib/config";

export const auth = betterAuth({
  basePath: "/",
  database: drizzleAdapter(db, {
    provider: "pg",
  }),
  secret: config.betterAuthSecret,
  baseURL: config.betterAuthUrl,
  trustedOrigins: [config.clientUrl],
  emailAndPassword: {
    enabled: true,
  },
  session: {
    expiresIn: 60 * 60 * 24 * 7,
    updateAge: 60 * 60 * 24,
    cookieCache: {
      enabled: true,
      maxAge: 60 * 5,
    },
  },
  advanced: {
    crossSubDomainCookies: {
      enabled: true,
    },
  },
  security: {
    csrf: {
      disabled: true,
    },
  },
  plugins: [
    openAPI(),
    magicLink({
      expiresIn: 60 * 60, // 1 hour
      rateLimit: {
        window: 60, // 1 minute
        max: 5, // 5 requests per minute
      },

      storeToken: "hashed", // Store tokens as hashed in the database
      sendMagicLink: async ({ email, url }) => {
        console.log("Magic link sent to:", email);
        console.log("Magic link URL:", url);
      },
    }),
    oAuthProxy({
      productionURL: config.clientUrl,
      currentURL: config.betterAuthUrl,
    }),
  ],
  emailVerification: {
    sendOnSignUp: true,
    autoSignInAfterVerification: true,

    sendVerificationEmail: async ({ user, url }) => {
      console.log("Email verification link:", url, user.email);
    },
    afterEmailVerification: async (user, request) => {
      console.log("Email verified for user:", user.email);
    },
  },
});
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Kinfe123**
The issue occurs when the baseURL has a root pathname ("/"), causing double slashes in URL construction that result in malformed magic link URLs. The fix treats root pathnames as empty strings, preventing the double slash issue and ensuring proper URL construction with the correct host and port information.

closes #3759

### CODE REVIEW

File: packages/better-auth/src/plugins/magic-link/index.ts [hunk 1]
```diff
@@ -190,8 +190,10 @@ export const magicLink = (options: MagicLinkopts) => {
 						ctx,
 					);
 					const realBaseURL = new URL(ctx.context.baseURL);
+					const pathname =
+						realBaseURL.pathname === "/" ? "" : realBaseURL.pathname;
```
Comment (Bekacru) [inline packages/better-auth/src/plugins/magic-link/index.ts:194]: I think this sohuld work
```suggestion
					const url = new URL("/magic-link/verify", ctx.context.baseURL);
```

File: packages/better-auth/src/plugins/magic-link/index.ts [hunk 2]
```diff
@@ -190,8 +190,10 @@ export const magicLink = (options: MagicLinkopts) => {
...
 					const url = new URL(
-						`${realBaseURL.pathname}/magic-link/verify`,
+						`${pathname}/magic-link/verify`,
 						realBaseURL.origin,
 					);
```
Comment (Bekacru) [inline packages/better-auth/src/plugins/magic-link/index.ts]:
```suggestion
```

File: packages/better-auth/src/plugins/magic-link/index.ts [hunk 3]
```diff
@@ -190,8 +190,10 @@ export const magicLink = (options: MagicLinkopts) => {
 						ctx,
 					);
 					const realBaseURL = new URL(ctx.context.baseURL);
+					const pathname =
+						realBaseURL.pathname === "/" ? "" : realBaseURL.pathname;
 					const url = new URL(
```
Comment (Bekacru) [inline packages/better-auth/src/plugins/magic-link/index.ts:196]:
```suggestion
```

**Comment by olingern** [comment]
This looks like it doesn't take into account `basePath` that all the endpoints are prefixed with. Shouldn't it be prepended?

```
export const auth = betterAuth({
  basePath: "/auth/api",
  ```
  
 I've ended up doing this most places in my code when I need links

```
if (url.includes("magic-link")) {
  const magicLinkUrl = url.split("/magic-link/")[1];
  const link = `${config.appUrl}/auth/api/magic-link/${magicLinkUrl}`;
}
```

**Comment by Kinfe123** [comment]
@Bekacru When you pass a relative path that starts with / (like "/magic-link/verify") to the URL constructor along with a base URL, the pathname in the base is discarded, and only the origin is used. like it will become `http://localhost:3000/magic-link/verify` discarding the `/api/auth` in baseURL. so thats why we are constructing the baseURL again to make sure those pathname are not overriden.

File: packages/better-auth/src/plugins/magic-link/magic-link.test.ts [hunk 4]
```diff
@@ -32,13 +32,15 @@ describe("magic link", async () => {
...
-		baseURL: "http://localhost:3000/api/auth",
+		baseURL: "http://localhost:3000",
+		basePath: "/api/auth",
 	});
 
 	it("should send magic link", async () => {
 		await client.signIn.magicLink({
 			email: testUser.email,
 		});
+		console.log(verificationEmail);
```
Comment (himself65) [inline packages/better-auth/src/plugins/magic-link/magic-link.test.ts:43]: no console.log?

Comment (Bekacru) [reply packages/better-auth/src/plugins/magic-link/magic-link.test.ts:43]: yeah. we probably should have linting rule for this
